# Configuration for production-ready model with all features
defaults:  
  - config.yaml

model:
  type: "advanced"
  text_encoder: "hybrid"  # combine TF-IDF and transformers
  use_graph_features: true
  horizons: [6, 12, 24]

text:
  model_name: "sentence-transformers/bge-base-en-v1.5"  # better quality
  max_features: 50000
  n_components: 512

data:
  limit: null  # no limit - use all available data
  
evaluation:
  ranking_metrics: true
  uncertainty_metrics: true
  explanation_samples: 500
